[build]
command = "hugo --gc --themesDir themes/"

[build.environment]
HUGO_THEME = "repo"

[context.production.environment]
HUGO_VERSION = "0.56.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.56.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --themesDir themes/ --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.56.3"

[context.branch-deploy]
command = "hugo --gc --themesDir themes/ -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.56.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

